resources:
  repositories:
    - repository: github
      endpoint: github
      trigger: none
      name: leriksen/azdo_copy_file_task
      type: github

pool: ipam-devops

stages:
  - stage: artifact
    displayName: Create Artifact
    jobs:
      - job: artifact
        displayName: Create Artifact
        steps:
          - task: CopyFiles@2
            displayName: Copy Files
            inputs:
              Contents: |
                **/*
                !.git/**/*
              TargetFolder: project_output
              CleanTargetFolder: true
          
          - task: ArchiveFiles@2
            displayName: Create project zip
            inputs:
              rootFolderOrFile: $(System.DefaultWorkingDirectory)/project_output
              includeRootFolder: true
              archiveType: zip
              archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
              replaceExistingArchive: true

          - task: PublishPipelineArtifact@1
            displayName: Publish project zip artifact
            inputs:
              targetPath: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
              artifact: $(logicAppCIArtifactName)
              publishLocation: pipeline